prod:
  hosts:
    hubble.zavadil.eu:
      target_dir: /opt/okarina
      application_files: conf/prod
      service_name: okarina
      spring_env: prod


test:
  hosts:
    hubble.zavadil.eu:
      target_dir: /opt/okarina-test
      application_files: conf/test
      service_name: okarina-test
      spring_env: test
      proxy_port: 8081
      domain: okarina.zavadil.eu
