services:
  dev-db:
    image: postgres:17.2-alpine
    container_name: ocr-dev-db
    environment:
      - POSTGRES_USER=ocr
      - POSTGRES_PASSWORD=ocr
      - POSTGRES_DB=ocr
    ports:
      - 5432:5432
