### Probe - fragments
GET http://localhost:8080/api/probe/fragments

### Probe - document
GET http://localhost:8080/api/probe/document

### Document templates
GET http://localhost:8080/api/document-templates

### Document template
GET http://localhost:8080/api/document-templates/2
