### Image
GET {{url}}/api/admin/images?path=templates%5C1%5CScreenshot%202025-01-13%20164922.png
Accept: image/avif,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJhdWQiOiJPa2FyaW5hIiwiZXhwIjoxNzQyNDAyMjA1LjE1NzIyMDA3MiwiaWF0IjoxNzQyNDAxNjA1LjE1NzIxOTgwMSwic2NvIjpbImFkbWluOioiXX0.VutcvJSLdGnoSh_ErjV2759cpAtd5BQeELOsEKzrqrogxd-wMYzz-g4xQ50QLgvUQ9B0sGrEFXvN4x0rmjaMs8aoGkpr_5z2zbUHfapfNkPaDkptN8Jk_WG31LqP74gSd5I3wMGUkoX98hP-Uw-xzn5G4QNE8fyTERGP6v1Au3LTnk-WoQd-5XMon-IjiNhLu7NM2Rzv35tFc6evgayMEN1GgDYyfi6eI3g7zLHrQ_a0pJZ5Ht75A8CTIsUTfCRNGdRATA4UXOdZrx4ULQm2MyufKB7lNSIPBbEdIcysWIgcHwRqN2ZZjIQXc_8hqiAGaFZ0WFw8EmfXVPAdkS43Qg

### Image
GET {{url}}/api/admin/images?path=%5Cexamples%5Cjava-ocr-1.png&size=thumb
Content-Type: application/json
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJhdWQiOiJPa2FyaW5hIiwiZXhwIjoxNzQyNDEwMTUzLjY1OTAxMjI1NiwiaWF0IjoxNzQyNDA5NTUzLjY1OTAxMTc5NSwic2NvIjpbImFkbWluOioiXX0.DA1cUjFqhyf4TTutRyRblcpPtaThyzSmwLSJztIzpArQKCvQTTeSqUTH9WMW7P13OVO8LE5d529rLKWyvYgXVQZoWOI0XJKrSHDAL_FPKZZR3Zt3hsuKxdQiNZW5kMGFpzUJhbqASHr-WeoV3Mdg7_pMnRoFfszQM3hZ-qUSDIDH19D7Mga2M6gdWJp_KmEXCP86RLcvAJRiwYXhO2r6HYTHAJLT_um7wF50ZK20If0E04-o0z5yTdnJbbVZNP3Xwst52s_w_QqAxtuyiv6nla3WKb_vWPMQwkY8N0GQfN-NFmKs8qwkP1HDQ5SvYUH4mS95Heqvj_-Oy9pINLYV1A

### Image thumb
GET {{url}}/api/images?path=templates\153\artbreeder-composer-2024-12-14T20_14_32.037Z.jpeg&size=thumb
