### Status
GET {{url}}/api/status/stats

### Version
GET {{url}}/api/status/version

### Oauth
GET {{url}}/api/status/oauth/info

### Oauth - id token
POST {{oauthUrl}}/api/oauth/id-tokens/from-login
Content-Type: application/json

{
    "login": "{{login}}",
    "password": "{{password}}",
    "targetAudience": "Okarina"
}

### Obtain access token
POST {{oauthUrl}}/api/oauth/access-tokens/from-id-token
Content-Type: application/json

{
    "targetAudience": "Okarina",
    "idToken": "eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJhdWQiOiJPa2FyaW5hIiwiZXhwIjoxNzQyNDg3OTkxLjYwMjgzODA1MSwiaWF0IjoxNzQyNDAxNTkxLjYwMjgzNjMzOCwic3ViIjoiMSIsIm5hbSI6IkthcmVsIFphdmFkaWwifQ.JTRvbVA7TH9pnQmUmqQxCEvwcpuxXIf1uRfcx49r-hT46zuop-yTOef-67Vuw2MpIXlSp7OUVC7GZdBF7Rr8v4W18S7dD8g440VfT8NuhSTtWJqsLcYGNFmEFdbikOWNoNfW7CgJTsT_pQJgChI0TgudWXLRXUFtG-vJ68ggFdLcSBZzH83aShVVljvxxOPIRTDlcSAJMgUWMsxzwM1FCVMmSDD-2FJHf-ZEEubGpudHZ9oorWIAqg0sO7JrIIhXi6rMmRyi_Sqrm42FijJjarH94NhaaV5_gYHhUZJF7nZJOD3rmnOFdciQVAqhD8N-gEGj6IYrB0CLBCZB6dpgLw"
}

### Verify ID token
GET {{oauthUrl}}/api/oauth/id-tokens/verify/eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJhdWQiOiJPa2FyaW5hIiwiZXhwIjoxNzQyNDg3OTkxLjYwMjgzODA1MSwiaWF0IjoxNzQyNDAxNTkxLjYwMjgzNjMzOCwic3ViIjoiMSIsIm5hbSI6IkthcmVsIFphdmFkaWwifQ.JTRvbVA7TH9pnQmUmqQxCEvwcpuxXIf1uRfcx49r-hT46zuop-yTOef-67Vuw2MpIXlSp7OUVC7GZdBF7Rr8v4W18S7dD8g440VfT8NuhSTtWJqsLcYGNFmEFdbikOWNoNfW7CgJTsT_pQJgChI0TgudWXLRXUFtG-vJ68ggFdLcSBZzH83aShVVljvxxOPIRTDlcSAJMgUWMsxzwM1FCVMmSDD-2FJHf-ZEEubGpudHZ9oorWIAqg0sO7JrIIhXi6rMmRyi_Sqrm42FijJjarH94NhaaV5_gYHhUZJF7nZJOD3rmnOFdciQVAqhD8N-gEGj6IYrB0CLBCZB6dpgLw
