### Status
GET {{url}}/api/status/stats

### Version
GET {{url}}/api/status/version

### Oauth
GET {{url}}/api/status/oauth/info

### Oauth - id token
POST {{oauthUrl}}/api/oauth/id-tokens/from-login
Content-Type: application/json

{
    "login": "{{login}}",
    "password": "{{password}}",
    "targetAudience": "Okarina"
}

### Obtain access token
POST {{oauthUrl}}/api/oauth/access-tokens/from-id-token
Content-Type: application/json

{
    "targetAudience": "Okarina",
    "idToken": "eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJhdWQiOiJPa2FyaW5hIiwiZXhwIjoxNzQyNDg3OTkxLjYwMjgzODA1MSwiaWF0IjoxNzQyNDAxNTkxLjYwMjgzNjMzOCwic3ViIjoiMSIsIm5hbSI6IkthcmVsIFphdmFkaWwifQ.JTRvbVA7TH9pnQmUmqQxCEvwcpuxXIf1uRfcx49r-hT46zuop-yTOef-67Vuw2MpIXlSp7OUVC7GZdBF7Rr8v4W18S7dD8g440VfT8NuhSTtWJqsLcYGNFmEFdbikOWNoNfW7CgJTsT_pQJgChI0TgudWXLRXUFtG-vJ68ggFdLcSBZzH83aShVVljvxxOPIRTDlcSAJMgUWMsxzwM1FCVMmSDD-2FJHf-ZEEubGpudHZ9oorWIAqg0sO7JrIIhXi6rMmRyi_Sqrm42FijJjarH94NhaaV5_gYHhUZJF7nZJOD3rmnOFdciQVAqhD8N-gEGj6IYrB0CLBCZB6dpgLw"
}

### Verify ID token
GET {{oauthUrl}}/api/oauth/id-tokens/verify/eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJhdWQiOiJPa2FyaW5hIiwiZXhwIjoxNzQyMzI5MjAxLjE5NDc2MzM1NCwiaWF0IjoxNzQyMzI4NjAxLjE5NDc2MjQ1Mywic2NvIjpbImFkbWluOioiXX0.T0SbyGA3ceFTuXfvx3r9Ckh4RIQlw9cdGRss5pFeLLlWQcwyVs78Qh43kLhxM82SJmPkTajEHq7At29ci17k3C72cl55L8qQFxn8qvHrzAcOp5zLRbcAknhJwhfB6oVqEvTC5sEav4D3d3fBkGlGJ5p11Z7QtKU8FfSZ-EfBVakcZGC2O9bx2vxotAWoX2m4rv9P2vB3Ds2v1woDtbEgn9LHFCGL3OGaixs3-5TYOW1uMGPmrevXJh_mFiFv_pVAlCsRumGfL8JYLhu6v_mjiHHsTWJqHDjoSCPq1F414_PGazaI-oW-Yslqd-Yu0LkIAjRCWv0YZlBE0X65xSCvBQ
