### Templates
GET {{url}}/api/admin/document-templates
Authorization: Bearer eyJraWQiOiJrMSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJhdWQiOiJPa2FyaW5hIiwiZXhwIjoxNzQyMzI5ODczLjc3NjM1NTc5MywiaWF0IjoxNzQyMzI5MjczLjc3NjM1NTQ4Miwic2NvIjpbImFkbWluOioiXX0.vDq6d2iGR6Pwg_PBXzxCTwwQc-rEKEwxCqR3DEm4MN0vhMpX3c0h5RFMKYartnfHUb7ohh6Vw9etA7LnYJYyU1ihj034eo71WwH6B1uWq_ajI2R2Bc6q634ODfcrE-DK1v4XfM0EgKA3Qt8wD475S6EuCm2rEAcroiYrS2shCkUR06lPE6HbZuchvjjPrDalLfNeBmFWUUxSUlutXh98J8rnv8iJ_D3fxo89sp-OeNuOWhX9YB7pT_gJwq1zigfQjvcgQexc7orMDZK2a1vNlp265ycuCS4Ep7CmcnSKMQYru1oaNgcImAXO6IG8AzDHyrMMzEaWrjRwMt-0y1EVGw

### Template
GET {{url}}/api/document-templates/1
